version: '3'
services:
  bundle_server:
    image: nginx:1.20.0-alpine
    volumes:
      - ./bundles/:/usr/share/nginx/html/

  opa:
    build:
      context: .
      dockerfile: ./docker/opa/Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - bundle_server

  gql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - opa
